### ISSUE TITLE
🐛 Fix build bustage of FunFuzz 

### ISSUE THREAD

**Issue by posidron** [MozillaSecurity/orion#32]
https://travis-ci.org/MozillaSecurity/orion/jobs/495171136#L9078

```
+ apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
Warning: apt-key output should not be parsed (stdout is not a terminal)
Executing: /tmp/apt-key-gpghome.wFqZWlFnRp/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 8B48AD6246925553
gpg: key 8B48AD6246925553: 27 signatures not checked due to missing keys
gpg: key 8B48AD6246925553: public key "Debian Archive Automatic Signing Key (7.0/wheezy) <ftpmaster@debian.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
+ echo 'deb http://ftp.us.debian.org/debian testing main contrib non-free'
+ apt-get update -y -qq
W: GPG error: http://ftp.us.debian.org/debian testing InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7638D0442B90D010 NO_PUBKEY 04EE7237B7D453EC
E: The repository 'http://ftp.us.debian.org/debian testing InRelease' is not signed.
The command '/bin/sh -c /tmp/recipes/install_prerequisites.sh     && rm -f /tmp/recipes/install_prerequisites.sh     && chown -R worker:worker /home/worker' returned a non-zero code: 100

**Comment by posidron** [comment]
It seems further that due to the amount of dependencies, the task for FunFuzz consumes too much time / more than allowed: https://travis-ci.org/MozillaSecurity/orion/builds/493489481#L9077 and we receive a `The job exceeded the maximum time limit for jobs, and has been terminated.` error. If possible strip out all stuff which is not required for installation and remove all stuff which ain't required for for running the container and the task within.

We can look at the work week to create a multi-stage build out of it. Which would also benefit that you do not constantly need to download the stuff on each re-build. It seems to be better when you put each recipe into an individual RUN command - to make use of caching. A relatively good example is the Dockerfile for Windows.

**Comment by nth10sd** [comment]
A couple of things:

* funfuzz only kicks in from line 9084 onwards. I'm not sure how much time is left for funfuzz in the test suite by then.
* Weren't we saying to reduce the number of RUN commands? That was why we aimed to push for 1 or 2 RUN commands only, and yes at the expense of caching. Are we reversing this?
* The Orion testsuite on Travis lumps all the projects into 1 work item. Should we look into having multiple work items for the testsuite? i.e. have 1 test run only the FuzzOS Dockerfile, 1 test to run only the Grizzly items, 1 test only for FuzzManager, 1 test only for funfuzz. Would this make sense?

Yes, we can continue this at the team meeting too, I doubt I'll have enough upcoming bandwidth.

**Comment by posidron** [comment]
This fixed the initial error. Yes, this is still true, the less RUN commands you have, the smaller the image, however, it starts to manifest more and more that the tradeoff in having slightly larger images and use caching is a huge benefit, especially for development and when downloading a massive amount of packages. The other point is taken care of now.
